// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/common/v1/common.proto

package io.opentelemetry.proto.common.v1;

/**
 * <pre>
 * A reference to an Entity.
 * Entity represents an object of interest associated with produced telemetry: e.g spans, metrics, profiles, or logs.
 * Status: [Development]
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.common.v1.EntityRef}
 */
public final class EntityRef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.common.v1.EntityRef)
    EntityRefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EntityRef.newBuilder() to construct.
  private EntityRef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EntityRef() {
    schemaUrl_ = "";
    type_ = "";
    idKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    descriptionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EntityRef();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EntityRef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            schemaUrl_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              idKeys_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            idKeys_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              descriptionKeys_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            descriptionKeys_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        idKeys_ = idKeys_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        descriptionKeys_ = descriptionKeys_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentelemetry.proto.common.v1.CommonProto.internal_static_opentelemetry_proto_common_v1_EntityRef_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentelemetry.proto.common.v1.CommonProto.internal_static_opentelemetry_proto_common_v1_EntityRef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentelemetry.proto.common.v1.EntityRef.class, io.opentelemetry.proto.common.v1.EntityRef.Builder.class);
  }

  public static final int SCHEMA_URL_FIELD_NUMBER = 1;
  private volatile java.lang.Object schemaUrl_;
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the entity data
   * is recorded in. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in this message and to the Resource attributes
   * referenced by id_keys and description_keys.
   * TODO: discuss if we are happy with this somewhat complicated definition of what
   * the schema_url applies to.
   * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
   * </pre>
   *
   * <code>string schema_url = 1;</code>
   * @return The schemaUrl.
   */
  @java.lang.Override
  public java.lang.String getSchemaUrl() {
    java.lang.Object ref = schemaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the entity data
   * is recorded in. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in this message and to the Resource attributes
   * referenced by id_keys and description_keys.
   * TODO: discuss if we are happy with this somewhat complicated definition of what
   * the schema_url applies to.
   * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
   * </pre>
   *
   * <code>string schema_url = 1;</code>
   * @return The bytes for schemaUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaUrlBytes() {
    java.lang.Object ref = schemaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   * Defines the type of the entity. MUST not change during the lifetime of the entity.
   * For example: "service" or "host". This field is required and MUST not be empty
   * for valid entities.
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Defines the type of the entity. MUST not change during the lifetime of the entity.
   * For example: "service" or "host". This field is required and MUST not be empty
   * for valid entities.
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_KEYS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList idKeys_;
  /**
   * <pre>
   * Attribute Keys that identify the entity.
   * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string id_keys = 3;</code>
   * @return A list containing the idKeys.
   */
  public com.google.protobuf.ProtocolStringList
      getIdKeysList() {
    return idKeys_;
  }
  /**
   * <pre>
   * Attribute Keys that identify the entity.
   * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string id_keys = 3;</code>
   * @return The count of idKeys.
   */
  public int getIdKeysCount() {
    return idKeys_.size();
  }
  /**
   * <pre>
   * Attribute Keys that identify the entity.
   * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string id_keys = 3;</code>
   * @param index The index of the element to return.
   * @return The idKeys at the given index.
   */
  public java.lang.String getIdKeys(int index) {
    return idKeys_.get(index);
  }
  /**
   * <pre>
   * Attribute Keys that identify the entity.
   * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string id_keys = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the idKeys at the given index.
   */
  public com.google.protobuf.ByteString
      getIdKeysBytes(int index) {
    return idKeys_.getByteString(index);
  }

  public static final int DESCRIPTION_KEYS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList descriptionKeys_;
  /**
   * <pre>
   * Descriptive (non-identifying) attribute keys of the entity.
   * MAY change over the lifetime of the entity. MAY be empty.
   * These attribute keys are not part of entity's identity.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string description_keys = 4;</code>
   * @return A list containing the descriptionKeys.
   */
  public com.google.protobuf.ProtocolStringList
      getDescriptionKeysList() {
    return descriptionKeys_;
  }
  /**
   * <pre>
   * Descriptive (non-identifying) attribute keys of the entity.
   * MAY change over the lifetime of the entity. MAY be empty.
   * These attribute keys are not part of entity's identity.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string description_keys = 4;</code>
   * @return The count of descriptionKeys.
   */
  public int getDescriptionKeysCount() {
    return descriptionKeys_.size();
  }
  /**
   * <pre>
   * Descriptive (non-identifying) attribute keys of the entity.
   * MAY change over the lifetime of the entity. MAY be empty.
   * These attribute keys are not part of entity's identity.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string description_keys = 4;</code>
   * @param index The index of the element to return.
   * @return The descriptionKeys at the given index.
   */
  public java.lang.String getDescriptionKeys(int index) {
    return descriptionKeys_.get(index);
  }
  /**
   * <pre>
   * Descriptive (non-identifying) attribute keys of the entity.
   * MAY change over the lifetime of the entity. MAY be empty.
   * These attribute keys are not part of entity's identity.
   * These keys MUST exist in the containing {message}.attributes.
   * </pre>
   *
   * <code>repeated string description_keys = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the descriptionKeys at the given index.
   */
  public com.google.protobuf.ByteString
      getDescriptionKeysBytes(int index) {
    return descriptionKeys_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schemaUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    for (int i = 0; i < idKeys_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, idKeys_.getRaw(i));
    }
    for (int i = 0; i < descriptionKeys_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, descriptionKeys_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schemaUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < idKeys_.size(); i++) {
        dataSize += computeStringSizeNoTag(idKeys_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIdKeysList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < descriptionKeys_.size(); i++) {
        dataSize += computeStringSizeNoTag(descriptionKeys_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDescriptionKeysList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentelemetry.proto.common.v1.EntityRef)) {
      return super.equals(obj);
    }
    io.opentelemetry.proto.common.v1.EntityRef other = (io.opentelemetry.proto.common.v1.EntityRef) obj;

    if (!getSchemaUrl()
        .equals(other.getSchemaUrl())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getIdKeysList()
        .equals(other.getIdKeysList())) return false;
    if (!getDescriptionKeysList()
        .equals(other.getDescriptionKeysList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEMA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaUrl().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (getIdKeysCount() > 0) {
      hash = (37 * hash) + ID_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getIdKeysList().hashCode();
    }
    if (getDescriptionKeysCount() > 0) {
      hash = (37 * hash) + DESCRIPTION_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getDescriptionKeysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.common.v1.EntityRef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentelemetry.proto.common.v1.EntityRef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A reference to an Entity.
   * Entity represents an object of interest associated with produced telemetry: e.g spans, metrics, profiles, or logs.
   * Status: [Development]
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.common.v1.EntityRef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.common.v1.EntityRef)
      io.opentelemetry.proto.common.v1.EntityRefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentelemetry.proto.common.v1.CommonProto.internal_static_opentelemetry_proto_common_v1_EntityRef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentelemetry.proto.common.v1.CommonProto.internal_static_opentelemetry_proto_common_v1_EntityRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentelemetry.proto.common.v1.EntityRef.class, io.opentelemetry.proto.common.v1.EntityRef.Builder.class);
    }

    // Construct using io.opentelemetry.proto.common.v1.EntityRef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      schemaUrl_ = "";

      type_ = "";

      idKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      descriptionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentelemetry.proto.common.v1.CommonProto.internal_static_opentelemetry_proto_common_v1_EntityRef_descriptor;
    }

    @java.lang.Override
    public io.opentelemetry.proto.common.v1.EntityRef getDefaultInstanceForType() {
      return io.opentelemetry.proto.common.v1.EntityRef.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentelemetry.proto.common.v1.EntityRef build() {
      io.opentelemetry.proto.common.v1.EntityRef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentelemetry.proto.common.v1.EntityRef buildPartial() {
      io.opentelemetry.proto.common.v1.EntityRef result = new io.opentelemetry.proto.common.v1.EntityRef(this);
      int from_bitField0_ = bitField0_;
      result.schemaUrl_ = schemaUrl_;
      result.type_ = type_;
      if (((bitField0_ & 0x00000001) != 0)) {
        idKeys_ = idKeys_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.idKeys_ = idKeys_;
      if (((bitField0_ & 0x00000002) != 0)) {
        descriptionKeys_ = descriptionKeys_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.descriptionKeys_ = descriptionKeys_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentelemetry.proto.common.v1.EntityRef) {
        return mergeFrom((io.opentelemetry.proto.common.v1.EntityRef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentelemetry.proto.common.v1.EntityRef other) {
      if (other == io.opentelemetry.proto.common.v1.EntityRef.getDefaultInstance()) return this;
      if (!other.getSchemaUrl().isEmpty()) {
        schemaUrl_ = other.schemaUrl_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.idKeys_.isEmpty()) {
        if (idKeys_.isEmpty()) {
          idKeys_ = other.idKeys_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIdKeysIsMutable();
          idKeys_.addAll(other.idKeys_);
        }
        onChanged();
      }
      if (!other.descriptionKeys_.isEmpty()) {
        if (descriptionKeys_.isEmpty()) {
          descriptionKeys_ = other.descriptionKeys_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDescriptionKeysIsMutable();
          descriptionKeys_.addAll(other.descriptionKeys_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opentelemetry.proto.common.v1.EntityRef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opentelemetry.proto.common.v1.EntityRef) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object schemaUrl_ = "";
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the entity data
     * is recorded in. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in this message and to the Resource attributes
     * referenced by id_keys and description_keys.
     * TODO: discuss if we are happy with this somewhat complicated definition of what
     * the schema_url applies to.
     * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
     * </pre>
     *
     * <code>string schema_url = 1;</code>
     * @return The schemaUrl.
     */
    public java.lang.String getSchemaUrl() {
      java.lang.Object ref = schemaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the entity data
     * is recorded in. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in this message and to the Resource attributes
     * referenced by id_keys and description_keys.
     * TODO: discuss if we are happy with this somewhat complicated definition of what
     * the schema_url applies to.
     * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
     * </pre>
     *
     * <code>string schema_url = 1;</code>
     * @return The bytes for schemaUrl.
     */
    public com.google.protobuf.ByteString
        getSchemaUrlBytes() {
      java.lang.Object ref = schemaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the entity data
     * is recorded in. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in this message and to the Resource attributes
     * referenced by id_keys and description_keys.
     * TODO: discuss if we are happy with this somewhat complicated definition of what
     * the schema_url applies to.
     * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
     * </pre>
     *
     * <code>string schema_url = 1;</code>
     * @param value The schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the entity data
     * is recorded in. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in this message and to the Resource attributes
     * referenced by id_keys and description_keys.
     * TODO: discuss if we are happy with this somewhat complicated definition of what
     * the schema_url applies to.
     * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
     * </pre>
     *
     * <code>string schema_url = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaUrl() {
      
      schemaUrl_ = getDefaultInstance().getSchemaUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the entity data
     * is recorded in. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in this message and to the Resource attributes
     * referenced by id_keys and description_keys.
     * TODO: discuss if we are happy with this somewhat complicated definition of what
     * the schema_url applies to.
     * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
     * </pre>
     *
     * <code>string schema_url = 1;</code>
     * @param value The bytes for schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schemaUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * Defines the type of the entity. MUST not change during the lifetime of the entity.
     * For example: "service" or "host". This field is required and MUST not be empty
     * for valid entities.
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Defines the type of the entity. MUST not change during the lifetime of the entity.
     * For example: "service" or "host". This field is required and MUST not be empty
     * for valid entities.
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Defines the type of the entity. MUST not change during the lifetime of the entity.
     * For example: "service" or "host". This field is required and MUST not be empty
     * for valid entities.
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defines the type of the entity. MUST not change during the lifetime of the entity.
     * For example: "service" or "host". This field is required and MUST not be empty
     * for valid entities.
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defines the type of the entity. MUST not change during the lifetime of the entity.
     * For example: "service" or "host". This field is required and MUST not be empty
     * for valid entities.
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList idKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIdKeysIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        idKeys_ = new com.google.protobuf.LazyStringArrayList(idKeys_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @return A list containing the idKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getIdKeysList() {
      return idKeys_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @return The count of idKeys.
     */
    public int getIdKeysCount() {
      return idKeys_.size();
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @param index The index of the element to return.
     * @return The idKeys at the given index.
     */
    public java.lang.String getIdKeys(int index) {
      return idKeys_.get(index);
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the idKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getIdKeysBytes(int index) {
      return idKeys_.getByteString(index);
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @param index The index to set the value at.
     * @param value The idKeys to set.
     * @return This builder for chaining.
     */
    public Builder setIdKeys(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdKeysIsMutable();
      idKeys_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @param value The idKeys to add.
     * @return This builder for chaining.
     */
    public Builder addIdKeys(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdKeysIsMutable();
      idKeys_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @param values The idKeys to add.
     * @return This builder for chaining.
     */
    public Builder addAllIdKeys(
        java.lang.Iterable<java.lang.String> values) {
      ensureIdKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, idKeys_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdKeys() {
      idKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Attribute Keys that identify the entity.
     * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string id_keys = 3;</code>
     * @param value The bytes of the idKeys to add.
     * @return This builder for chaining.
     */
    public Builder addIdKeysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIdKeysIsMutable();
      idKeys_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList descriptionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDescriptionKeysIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        descriptionKeys_ = new com.google.protobuf.LazyStringArrayList(descriptionKeys_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @return A list containing the descriptionKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getDescriptionKeysList() {
      return descriptionKeys_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @return The count of descriptionKeys.
     */
    public int getDescriptionKeysCount() {
      return descriptionKeys_.size();
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @param index The index of the element to return.
     * @return The descriptionKeys at the given index.
     */
    public java.lang.String getDescriptionKeys(int index) {
      return descriptionKeys_.get(index);
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the descriptionKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getDescriptionKeysBytes(int index) {
      return descriptionKeys_.getByteString(index);
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @param index The index to set the value at.
     * @param value The descriptionKeys to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionKeys(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDescriptionKeysIsMutable();
      descriptionKeys_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @param value The descriptionKeys to add.
     * @return This builder for chaining.
     */
    public Builder addDescriptionKeys(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDescriptionKeysIsMutable();
      descriptionKeys_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @param values The descriptionKeys to add.
     * @return This builder for chaining.
     */
    public Builder addAllDescriptionKeys(
        java.lang.Iterable<java.lang.String> values) {
      ensureDescriptionKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, descriptionKeys_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescriptionKeys() {
      descriptionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Descriptive (non-identifying) attribute keys of the entity.
     * MAY change over the lifetime of the entity. MAY be empty.
     * These attribute keys are not part of entity's identity.
     * These keys MUST exist in the containing {message}.attributes.
     * </pre>
     *
     * <code>repeated string description_keys = 4;</code>
     * @param value The bytes of the descriptionKeys to add.
     * @return This builder for chaining.
     */
    public Builder addDescriptionKeysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDescriptionKeysIsMutable();
      descriptionKeys_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.common.v1.EntityRef)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.common.v1.EntityRef)
  private static final io.opentelemetry.proto.common.v1.EntityRef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentelemetry.proto.common.v1.EntityRef();
  }

  public static io.opentelemetry.proto.common.v1.EntityRef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EntityRef>
      PARSER = new com.google.protobuf.AbstractParser<EntityRef>() {
    @java.lang.Override
    public EntityRef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EntityRef(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EntityRef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EntityRef> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentelemetry.proto.common.v1.EntityRef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

