header:
  - paths:
      - 'src/jattach'
    license:
      content: |
        Copyright The jattach authors
        SPDX-License-Identifier: Apache-2.0

    comment: on-failure

  - paths:
      - 'src'
      - 'test'
    paths-ignore:
      - 'src/jattach'
      - 'src/res'
      - '**/MANIFEST.MF'
    license:
      content: |
        Copyright The async-profiler authors
        SPDX-License-Identifier: Apache-2.0

    comment: on-failure
