// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

/**
 * <pre>
 * Represents a mapping between Attribute Keys and Units.
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.profiles.v1development.AttributeUnit}
 */
public final class AttributeUnit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.profiles.v1development.AttributeUnit)
    AttributeUnitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AttributeUnit.newBuilder() to construct.
  private AttributeUnit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AttributeUnit() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AttributeUnit();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_AttributeUnit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_AttributeUnit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentelemetry.proto.profiles.v1development.AttributeUnit.class, io.opentelemetry.proto.profiles.v1development.AttributeUnit.Builder.class);
  }

  public static final int ATTRIBUTE_KEY_STRINDEX_FIELD_NUMBER = 1;
  private int attributeKeyStrindex_ = 0;
  /**
   * <pre>
   * Index into string table.
   * </pre>
   *
   * <code>int32 attribute_key_strindex = 1;</code>
   * @return The attributeKeyStrindex.
   */
  @java.lang.Override
  public int getAttributeKeyStrindex() {
    return attributeKeyStrindex_;
  }

  public static final int UNIT_STRINDEX_FIELD_NUMBER = 2;
  private int unitStrindex_ = 0;
  /**
   * <pre>
   * Index into string table.
   * </pre>
   *
   * <code>int32 unit_strindex = 2;</code>
   * @return The unitStrindex.
   */
  @java.lang.Override
  public int getUnitStrindex() {
    return unitStrindex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (attributeKeyStrindex_ != 0) {
      output.writeInt32(1, attributeKeyStrindex_);
    }
    if (unitStrindex_ != 0) {
      output.writeInt32(2, unitStrindex_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attributeKeyStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, attributeKeyStrindex_);
    }
    if (unitStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, unitStrindex_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentelemetry.proto.profiles.v1development.AttributeUnit)) {
      return super.equals(obj);
    }
    io.opentelemetry.proto.profiles.v1development.AttributeUnit other = (io.opentelemetry.proto.profiles.v1development.AttributeUnit) obj;

    if (getAttributeKeyStrindex()
        != other.getAttributeKeyStrindex()) return false;
    if (getUnitStrindex()
        != other.getUnitStrindex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ATTRIBUTE_KEY_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getAttributeKeyStrindex();
    hash = (37 * hash) + UNIT_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getUnitStrindex();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentelemetry.proto.profiles.v1development.AttributeUnit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a mapping between Attribute Keys and Units.
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.profiles.v1development.AttributeUnit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.profiles.v1development.AttributeUnit)
      io.opentelemetry.proto.profiles.v1development.AttributeUnitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_AttributeUnit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_AttributeUnit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentelemetry.proto.profiles.v1development.AttributeUnit.class, io.opentelemetry.proto.profiles.v1development.AttributeUnit.Builder.class);
    }

    // Construct using io.opentelemetry.proto.profiles.v1development.AttributeUnit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      attributeKeyStrindex_ = 0;
      unitStrindex_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_AttributeUnit_descriptor;
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.AttributeUnit getDefaultInstanceForType() {
      return io.opentelemetry.proto.profiles.v1development.AttributeUnit.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.AttributeUnit build() {
      io.opentelemetry.proto.profiles.v1development.AttributeUnit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.AttributeUnit buildPartial() {
      io.opentelemetry.proto.profiles.v1development.AttributeUnit result = new io.opentelemetry.proto.profiles.v1development.AttributeUnit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentelemetry.proto.profiles.v1development.AttributeUnit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.attributeKeyStrindex_ = attributeKeyStrindex_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.unitStrindex_ = unitStrindex_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentelemetry.proto.profiles.v1development.AttributeUnit) {
        return mergeFrom((io.opentelemetry.proto.profiles.v1development.AttributeUnit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentelemetry.proto.profiles.v1development.AttributeUnit other) {
      if (other == io.opentelemetry.proto.profiles.v1development.AttributeUnit.getDefaultInstance()) return this;
      if (other.getAttributeKeyStrindex() != 0) {
        setAttributeKeyStrindex(other.getAttributeKeyStrindex());
      }
      if (other.getUnitStrindex() != 0) {
        setUnitStrindex(other.getUnitStrindex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              attributeKeyStrindex_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              unitStrindex_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int attributeKeyStrindex_ ;
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 attribute_key_strindex = 1;</code>
     * @return The attributeKeyStrindex.
     */
    @java.lang.Override
    public int getAttributeKeyStrindex() {
      return attributeKeyStrindex_;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 attribute_key_strindex = 1;</code>
     * @param value The attributeKeyStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setAttributeKeyStrindex(int value) {

      attributeKeyStrindex_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 attribute_key_strindex = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttributeKeyStrindex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      attributeKeyStrindex_ = 0;
      onChanged();
      return this;
    }

    private int unitStrindex_ ;
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 unit_strindex = 2;</code>
     * @return The unitStrindex.
     */
    @java.lang.Override
    public int getUnitStrindex() {
      return unitStrindex_;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 unit_strindex = 2;</code>
     * @param value The unitStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setUnitStrindex(int value) {

      unitStrindex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Index into string table.
     * </pre>
     *
     * <code>int32 unit_strindex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitStrindex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      unitStrindex_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.profiles.v1development.AttributeUnit)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.profiles.v1development.AttributeUnit)
  private static final io.opentelemetry.proto.profiles.v1development.AttributeUnit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentelemetry.proto.profiles.v1development.AttributeUnit();
  }

  public static io.opentelemetry.proto.profiles.v1development.AttributeUnit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttributeUnit>
      PARSER = new com.google.protobuf.AbstractParser<AttributeUnit>() {
    @java.lang.Override
    public AttributeUnit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AttributeUnit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttributeUnit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentelemetry.proto.profiles.v1development.AttributeUnit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

