// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

public interface FunctionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.profiles.v1development.Function)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Function name. Empty string if not available.
   * </pre>
   *
   * <code>int32 name_strindex = 1;</code>
   * @return The nameStrindex.
   */
  int getNameStrindex();

  /**
   * <pre>
   * Function name, as identified by the system. For instance,
   * it can be a C++ mangled name. Empty string if not available.
   * </pre>
   *
   * <code>int32 system_name_strindex = 2;</code>
   * @return The systemNameStrindex.
   */
  int getSystemNameStrindex();

  /**
   * <pre>
   * Source file containing the function. Empty string if not available.
   * </pre>
   *
   * <code>int32 filename_strindex = 3;</code>
   * @return The filenameStrindex.
   */
  int getFilenameStrindex();

  /**
   * <pre>
   * Line number in source file. 0 means unset.
   * </pre>
   *
   * <code>int64 start_line = 4;</code>
   * @return The startLine.
   */
  long getStartLine();
}
