// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

/**
 * <pre>
 * Describes a function, including its human-readable name, system name,
 * source file, and starting line number in the source.
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.profiles.v1development.Function}
 */
public final class Function extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.profiles.v1development.Function)
    FunctionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Function.newBuilder() to construct.
  private Function(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Function() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Function();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_Function_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_Function_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentelemetry.proto.profiles.v1development.Function.class, io.opentelemetry.proto.profiles.v1development.Function.Builder.class);
  }

  public static final int NAME_STRINDEX_FIELD_NUMBER = 1;
  private int nameStrindex_ = 0;
  /**
   * <pre>
   * Function name. Empty string if not available.
   * </pre>
   *
   * <code>int32 name_strindex = 1;</code>
   * @return The nameStrindex.
   */
  @java.lang.Override
  public int getNameStrindex() {
    return nameStrindex_;
  }

  public static final int SYSTEM_NAME_STRINDEX_FIELD_NUMBER = 2;
  private int systemNameStrindex_ = 0;
  /**
   * <pre>
   * Function name, as identified by the system. For instance,
   * it can be a C++ mangled name. Empty string if not available.
   * </pre>
   *
   * <code>int32 system_name_strindex = 2;</code>
   * @return The systemNameStrindex.
   */
  @java.lang.Override
  public int getSystemNameStrindex() {
    return systemNameStrindex_;
  }

  public static final int FILENAME_STRINDEX_FIELD_NUMBER = 3;
  private int filenameStrindex_ = 0;
  /**
   * <pre>
   * Source file containing the function. Empty string if not available.
   * </pre>
   *
   * <code>int32 filename_strindex = 3;</code>
   * @return The filenameStrindex.
   */
  @java.lang.Override
  public int getFilenameStrindex() {
    return filenameStrindex_;
  }

  public static final int START_LINE_FIELD_NUMBER = 4;
  private long startLine_ = 0L;
  /**
   * <pre>
   * Line number in source file. 0 means unset.
   * </pre>
   *
   * <code>int64 start_line = 4;</code>
   * @return The startLine.
   */
  @java.lang.Override
  public long getStartLine() {
    return startLine_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nameStrindex_ != 0) {
      output.writeInt32(1, nameStrindex_);
    }
    if (systemNameStrindex_ != 0) {
      output.writeInt32(2, systemNameStrindex_);
    }
    if (filenameStrindex_ != 0) {
      output.writeInt32(3, filenameStrindex_);
    }
    if (startLine_ != 0L) {
      output.writeInt64(4, startLine_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nameStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, nameStrindex_);
    }
    if (systemNameStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, systemNameStrindex_);
    }
    if (filenameStrindex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, filenameStrindex_);
    }
    if (startLine_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, startLine_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentelemetry.proto.profiles.v1development.Function)) {
      return super.equals(obj);
    }
    io.opentelemetry.proto.profiles.v1development.Function other = (io.opentelemetry.proto.profiles.v1development.Function) obj;

    if (getNameStrindex()
        != other.getNameStrindex()) return false;
    if (getSystemNameStrindex()
        != other.getSystemNameStrindex()) return false;
    if (getFilenameStrindex()
        != other.getFilenameStrindex()) return false;
    if (getStartLine()
        != other.getStartLine()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getNameStrindex();
    hash = (37 * hash) + SYSTEM_NAME_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getSystemNameStrindex();
    hash = (37 * hash) + FILENAME_STRINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getFilenameStrindex();
    hash = (37 * hash) + START_LINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartLine());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentelemetry.proto.profiles.v1development.Function parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentelemetry.proto.profiles.v1development.Function parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.Function parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentelemetry.proto.profiles.v1development.Function prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Describes a function, including its human-readable name, system name,
   * source file, and starting line number in the source.
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.profiles.v1development.Function}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.profiles.v1development.Function)
      io.opentelemetry.proto.profiles.v1development.FunctionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_Function_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_Function_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentelemetry.proto.profiles.v1development.Function.class, io.opentelemetry.proto.profiles.v1development.Function.Builder.class);
    }

    // Construct using io.opentelemetry.proto.profiles.v1development.Function.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      nameStrindex_ = 0;
      systemNameStrindex_ = 0;
      filenameStrindex_ = 0;
      startLine_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_Function_descriptor;
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.Function getDefaultInstanceForType() {
      return io.opentelemetry.proto.profiles.v1development.Function.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.Function build() {
      io.opentelemetry.proto.profiles.v1development.Function result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.Function buildPartial() {
      io.opentelemetry.proto.profiles.v1development.Function result = new io.opentelemetry.proto.profiles.v1development.Function(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentelemetry.proto.profiles.v1development.Function result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.nameStrindex_ = nameStrindex_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.systemNameStrindex_ = systemNameStrindex_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.filenameStrindex_ = filenameStrindex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.startLine_ = startLine_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentelemetry.proto.profiles.v1development.Function) {
        return mergeFrom((io.opentelemetry.proto.profiles.v1development.Function)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentelemetry.proto.profiles.v1development.Function other) {
      if (other == io.opentelemetry.proto.profiles.v1development.Function.getDefaultInstance()) return this;
      if (other.getNameStrindex() != 0) {
        setNameStrindex(other.getNameStrindex());
      }
      if (other.getSystemNameStrindex() != 0) {
        setSystemNameStrindex(other.getSystemNameStrindex());
      }
      if (other.getFilenameStrindex() != 0) {
        setFilenameStrindex(other.getFilenameStrindex());
      }
      if (other.getStartLine() != 0L) {
        setStartLine(other.getStartLine());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              nameStrindex_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              systemNameStrindex_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              filenameStrindex_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              startLine_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int nameStrindex_ ;
    /**
     * <pre>
     * Function name. Empty string if not available.
     * </pre>
     *
     * <code>int32 name_strindex = 1;</code>
     * @return The nameStrindex.
     */
    @java.lang.Override
    public int getNameStrindex() {
      return nameStrindex_;
    }
    /**
     * <pre>
     * Function name. Empty string if not available.
     * </pre>
     *
     * <code>int32 name_strindex = 1;</code>
     * @param value The nameStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setNameStrindex(int value) {

      nameStrindex_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Function name. Empty string if not available.
     * </pre>
     *
     * <code>int32 name_strindex = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNameStrindex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      nameStrindex_ = 0;
      onChanged();
      return this;
    }

    private int systemNameStrindex_ ;
    /**
     * <pre>
     * Function name, as identified by the system. For instance,
     * it can be a C++ mangled name. Empty string if not available.
     * </pre>
     *
     * <code>int32 system_name_strindex = 2;</code>
     * @return The systemNameStrindex.
     */
    @java.lang.Override
    public int getSystemNameStrindex() {
      return systemNameStrindex_;
    }
    /**
     * <pre>
     * Function name, as identified by the system. For instance,
     * it can be a C++ mangled name. Empty string if not available.
     * </pre>
     *
     * <code>int32 system_name_strindex = 2;</code>
     * @param value The systemNameStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setSystemNameStrindex(int value) {

      systemNameStrindex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Function name, as identified by the system. For instance,
     * it can be a C++ mangled name. Empty string if not available.
     * </pre>
     *
     * <code>int32 system_name_strindex = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemNameStrindex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      systemNameStrindex_ = 0;
      onChanged();
      return this;
    }

    private int filenameStrindex_ ;
    /**
     * <pre>
     * Source file containing the function. Empty string if not available.
     * </pre>
     *
     * <code>int32 filename_strindex = 3;</code>
     * @return The filenameStrindex.
     */
    @java.lang.Override
    public int getFilenameStrindex() {
      return filenameStrindex_;
    }
    /**
     * <pre>
     * Source file containing the function. Empty string if not available.
     * </pre>
     *
     * <code>int32 filename_strindex = 3;</code>
     * @param value The filenameStrindex to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameStrindex(int value) {

      filenameStrindex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Source file containing the function. Empty string if not available.
     * </pre>
     *
     * <code>int32 filename_strindex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilenameStrindex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      filenameStrindex_ = 0;
      onChanged();
      return this;
    }

    private long startLine_ ;
    /**
     * <pre>
     * Line number in source file. 0 means unset.
     * </pre>
     *
     * <code>int64 start_line = 4;</code>
     * @return The startLine.
     */
    @java.lang.Override
    public long getStartLine() {
      return startLine_;
    }
    /**
     * <pre>
     * Line number in source file. 0 means unset.
     * </pre>
     *
     * <code>int64 start_line = 4;</code>
     * @param value The startLine to set.
     * @return This builder for chaining.
     */
    public Builder setStartLine(long value) {

      startLine_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Line number in source file. 0 means unset.
     * </pre>
     *
     * <code>int64 start_line = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartLine() {
      bitField0_ = (bitField0_ & ~0x00000008);
      startLine_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.profiles.v1development.Function)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.profiles.v1development.Function)
  private static final io.opentelemetry.proto.profiles.v1development.Function DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentelemetry.proto.profiles.v1development.Function();
  }

  public static io.opentelemetry.proto.profiles.v1development.Function getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Function>
      PARSER = new com.google.protobuf.AbstractParser<Function>() {
    @java.lang.Override
    public Function parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Function> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Function> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentelemetry.proto.profiles.v1development.Function getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

