// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

public interface ProfilesDictionaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.profiles.v1development.ProfilesDictionary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Mappings from address ranges to the image/binary/library mapped
   * into that address range referenced by locations via Location.mapping_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
   */
  java.util.List<io.opentelemetry.proto.profiles.v1development.Mapping> 
      getMappingTableList();
  /**
   * <pre>
   * Mappings from address ranges to the image/binary/library mapped
   * into that address range referenced by locations via Location.mapping_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
   */
  io.opentelemetry.proto.profiles.v1development.Mapping getMappingTable(int index);
  /**
   * <pre>
   * Mappings from address ranges to the image/binary/library mapped
   * into that address range referenced by locations via Location.mapping_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
   */
  int getMappingTableCount();
  /**
   * <pre>
   * Mappings from address ranges to the image/binary/library mapped
   * into that address range referenced by locations via Location.mapping_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.profiles.v1development.MappingOrBuilder> 
      getMappingTableOrBuilderList();
  /**
   * <pre>
   * Mappings from address ranges to the image/binary/library mapped
   * into that address range referenced by locations via Location.mapping_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
   */
  io.opentelemetry.proto.profiles.v1development.MappingOrBuilder getMappingTableOrBuilder(
      int index);

  /**
   * <pre>
   * Locations referenced by samples via Profile.location_indices.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
   */
  java.util.List<io.opentelemetry.proto.profiles.v1development.Location> 
      getLocationTableList();
  /**
   * <pre>
   * Locations referenced by samples via Profile.location_indices.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
   */
  io.opentelemetry.proto.profiles.v1development.Location getLocationTable(int index);
  /**
   * <pre>
   * Locations referenced by samples via Profile.location_indices.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
   */
  int getLocationTableCount();
  /**
   * <pre>
   * Locations referenced by samples via Profile.location_indices.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.profiles.v1development.LocationOrBuilder> 
      getLocationTableOrBuilderList();
  /**
   * <pre>
   * Locations referenced by samples via Profile.location_indices.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
   */
  io.opentelemetry.proto.profiles.v1development.LocationOrBuilder getLocationTableOrBuilder(
      int index);

  /**
   * <pre>
   * Functions referenced by locations via Line.function_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
   */
  java.util.List<io.opentelemetry.proto.profiles.v1development.Function> 
      getFunctionTableList();
  /**
   * <pre>
   * Functions referenced by locations via Line.function_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
   */
  io.opentelemetry.proto.profiles.v1development.Function getFunctionTable(int index);
  /**
   * <pre>
   * Functions referenced by locations via Line.function_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
   */
  int getFunctionTableCount();
  /**
   * <pre>
   * Functions referenced by locations via Line.function_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.profiles.v1development.FunctionOrBuilder> 
      getFunctionTableOrBuilderList();
  /**
   * <pre>
   * Functions referenced by locations via Line.function_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
   */
  io.opentelemetry.proto.profiles.v1development.FunctionOrBuilder getFunctionTableOrBuilder(
      int index);

  /**
   * <pre>
   * Links referenced by samples via Sample.link_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
   */
  java.util.List<io.opentelemetry.proto.profiles.v1development.Link> 
      getLinkTableList();
  /**
   * <pre>
   * Links referenced by samples via Sample.link_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
   */
  io.opentelemetry.proto.profiles.v1development.Link getLinkTable(int index);
  /**
   * <pre>
   * Links referenced by samples via Sample.link_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
   */
  int getLinkTableCount();
  /**
   * <pre>
   * Links referenced by samples via Sample.link_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.profiles.v1development.LinkOrBuilder> 
      getLinkTableOrBuilderList();
  /**
   * <pre>
   * Links referenced by samples via Sample.link_index.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
   */
  io.opentelemetry.proto.profiles.v1development.LinkOrBuilder getLinkTableOrBuilder(
      int index);

  /**
   * <pre>
   * A common table for strings referenced by various messages.
   * string_table[0] must always be "".
   * </pre>
   *
   * <code>repeated string string_table = 5;</code>
   * @return A list containing the stringTable.
   */
  java.util.List<java.lang.String>
      getStringTableList();
  /**
   * <pre>
   * A common table for strings referenced by various messages.
   * string_table[0] must always be "".
   * </pre>
   *
   * <code>repeated string string_table = 5;</code>
   * @return The count of stringTable.
   */
  int getStringTableCount();
  /**
   * <pre>
   * A common table for strings referenced by various messages.
   * string_table[0] must always be "".
   * </pre>
   *
   * <code>repeated string string_table = 5;</code>
   * @param index The index of the element to return.
   * @return The stringTable at the given index.
   */
  java.lang.String getStringTable(int index);
  /**
   * <pre>
   * A common table for strings referenced by various messages.
   * string_table[0] must always be "".
   * </pre>
   *
   * <code>repeated string string_table = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stringTable at the given index.
   */
  com.google.protobuf.ByteString
      getStringTableBytes(int index);

  /**
   * <pre>
   * A common table for attributes referenced by various messages.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.common.v1.KeyValue attribute_table = 6;</code>
   */
  java.util.List<io.opentelemetry.proto.common.v1.KeyValue> 
      getAttributeTableList();
  /**
   * <pre>
   * A common table for attributes referenced by various messages.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.common.v1.KeyValue attribute_table = 6;</code>
   */
  io.opentelemetry.proto.common.v1.KeyValue getAttributeTable(int index);
  /**
   * <pre>
   * A common table for attributes referenced by various messages.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.common.v1.KeyValue attribute_table = 6;</code>
   */
  int getAttributeTableCount();
  /**
   * <pre>
   * A common table for attributes referenced by various messages.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.common.v1.KeyValue attribute_table = 6;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.common.v1.KeyValueOrBuilder> 
      getAttributeTableOrBuilderList();
  /**
   * <pre>
   * A common table for attributes referenced by various messages.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.common.v1.KeyValue attribute_table = 6;</code>
   */
  io.opentelemetry.proto.common.v1.KeyValueOrBuilder getAttributeTableOrBuilder(
      int index);

  /**
   * <pre>
   * Represents a mapping between Attribute Keys and Units.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.AttributeUnit attribute_units = 7;</code>
   */
  java.util.List<io.opentelemetry.proto.profiles.v1development.AttributeUnit> 
      getAttributeUnitsList();
  /**
   * <pre>
   * Represents a mapping between Attribute Keys and Units.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.AttributeUnit attribute_units = 7;</code>
   */
  io.opentelemetry.proto.profiles.v1development.AttributeUnit getAttributeUnits(int index);
  /**
   * <pre>
   * Represents a mapping between Attribute Keys and Units.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.AttributeUnit attribute_units = 7;</code>
   */
  int getAttributeUnitsCount();
  /**
   * <pre>
   * Represents a mapping between Attribute Keys and Units.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.AttributeUnit attribute_units = 7;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.profiles.v1development.AttributeUnitOrBuilder> 
      getAttributeUnitsOrBuilderList();
  /**
   * <pre>
   * Represents a mapping between Attribute Keys and Units.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.AttributeUnit attribute_units = 7;</code>
   */
  io.opentelemetry.proto.profiles.v1development.AttributeUnitOrBuilder getAttributeUnitsOrBuilder(
      int index);
}
