// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

public interface ResourceProfilesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.profiles.v1development.ResourceProfiles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <pre>
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return The resource.
   */
  io.opentelemetry.proto.resource.v1.Resource getResource();
  /**
   * <pre>
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   */
  io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  java.util.List<io.opentelemetry.proto.profiles.v1development.ScopeProfiles> 
      getScopeProfilesList();
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  io.opentelemetry.proto.profiles.v1development.ScopeProfiles getScopeProfiles(int index);
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  int getScopeProfilesCount();
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  java.util.List<? extends io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder> 
      getScopeProfilesOrBuilderList();
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder getScopeProfilesOrBuilder(
      int index);

  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_profiles" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The schemaUrl.
   */
  java.lang.String getSchemaUrl();
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_profiles" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The bytes for schemaUrl.
   */
  com.google.protobuf.ByteString
      getSchemaUrlBytes();
}
