// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package io.opentelemetry.proto.profiles.v1development;

/**
 * <pre>
 * A collection of ScopeProfiles from a Resource.
 * </pre>
 *
 * Protobuf type {@code opentelemetry.proto.profiles.v1development.ResourceProfiles}
 */
public final class ResourceProfiles extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.profiles.v1development.ResourceProfiles)
    ResourceProfilesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceProfiles.newBuilder() to construct.
  private ResourceProfiles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceProfiles() {
    scopeProfiles_ = java.util.Collections.emptyList();
    schemaUrl_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceProfiles();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceProfiles(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.opentelemetry.proto.resource.v1.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(io.opentelemetry.proto.resource.v1.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              scopeProfiles_ = new java.util.ArrayList<io.opentelemetry.proto.profiles.v1development.ScopeProfiles>();
              mutable_bitField0_ |= 0x00000001;
            }
            scopeProfiles_.add(
                input.readMessage(io.opentelemetry.proto.profiles.v1development.ScopeProfiles.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            schemaUrl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        scopeProfiles_ = java.util.Collections.unmodifiableList(scopeProfiles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ResourceProfiles_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ResourceProfiles_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentelemetry.proto.profiles.v1development.ResourceProfiles.class, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder.class);
  }

  public static final int RESOURCE_FIELD_NUMBER = 1;
  private io.opentelemetry.proto.resource.v1.Resource resource_;
  /**
   * <pre>
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <pre>
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return The resource.
   */
  @java.lang.Override
  public io.opentelemetry.proto.resource.v1.Resource getResource() {
    return resource_ == null ? io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <pre>
   * The resource for the profiles in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int SCOPE_PROFILES_FIELD_NUMBER = 2;
  private java.util.List<io.opentelemetry.proto.profiles.v1development.ScopeProfiles> scopeProfiles_;
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.opentelemetry.proto.profiles.v1development.ScopeProfiles> getScopeProfilesList() {
    return scopeProfiles_;
  }
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder> 
      getScopeProfilesOrBuilderList() {
    return scopeProfiles_;
  }
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  @java.lang.Override
  public int getScopeProfilesCount() {
    return scopeProfiles_.size();
  }
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.profiles.v1development.ScopeProfiles getScopeProfiles(int index) {
    return scopeProfiles_.get(index);
  }
  /**
   * <pre>
   * A list of ScopeProfiles that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
   */
  @java.lang.Override
  public io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder getScopeProfilesOrBuilder(
      int index) {
    return scopeProfiles_.get(index);
  }

  public static final int SCHEMA_URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object schemaUrl_;
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_profiles" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The schemaUrl.
   */
  @java.lang.Override
  public java.lang.String getSchemaUrl() {
    java.lang.Object ref = schemaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schemaUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The Schema URL, if known. This is the identifier of the Schema that the resource data
   * is recorded in. Notably, the last part of the URL path is the version number of the
   * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_profiles" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The bytes for schemaUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaUrlBytes() {
    java.lang.Object ref = schemaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schemaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    for (int i = 0; i < scopeProfiles_.size(); i++) {
      output.writeMessage(2, scopeProfiles_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, schemaUrl_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    for (int i = 0; i < scopeProfiles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, scopeProfiles_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schemaUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, schemaUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentelemetry.proto.profiles.v1development.ResourceProfiles)) {
      return super.equals(obj);
    }
    io.opentelemetry.proto.profiles.v1development.ResourceProfiles other = (io.opentelemetry.proto.profiles.v1development.ResourceProfiles) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getScopeProfilesList()
        .equals(other.getScopeProfilesList())) return false;
    if (!getSchemaUrl()
        .equals(other.getSchemaUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    if (getScopeProfilesCount() > 0) {
      hash = (37 * hash) + SCOPE_PROFILES_FIELD_NUMBER;
      hash = (53 * hash) + getScopeProfilesList().hashCode();
    }
    hash = (37 * hash) + SCHEMA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentelemetry.proto.profiles.v1development.ResourceProfiles prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A collection of ScopeProfiles from a Resource.
   * </pre>
   *
   * Protobuf type {@code opentelemetry.proto.profiles.v1development.ResourceProfiles}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.profiles.v1development.ResourceProfiles)
      io.opentelemetry.proto.profiles.v1development.ResourceProfilesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ResourceProfiles_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ResourceProfiles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentelemetry.proto.profiles.v1development.ResourceProfiles.class, io.opentelemetry.proto.profiles.v1development.ResourceProfiles.Builder.class);
    }

    // Construct using io.opentelemetry.proto.profiles.v1development.ResourceProfiles.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getScopeProfilesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      if (scopeProfilesBuilder_ == null) {
        scopeProfiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        scopeProfilesBuilder_.clear();
      }
      schemaUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentelemetry.proto.profiles.v1development.ProfilesProto.internal_static_opentelemetry_proto_profiles_v1development_ResourceProfiles_descriptor;
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles getDefaultInstanceForType() {
      return io.opentelemetry.proto.profiles.v1development.ResourceProfiles.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles build() {
      io.opentelemetry.proto.profiles.v1development.ResourceProfiles result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentelemetry.proto.profiles.v1development.ResourceProfiles buildPartial() {
      io.opentelemetry.proto.profiles.v1development.ResourceProfiles result = new io.opentelemetry.proto.profiles.v1development.ResourceProfiles(this);
      int from_bitField0_ = bitField0_;
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      if (scopeProfilesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          scopeProfiles_ = java.util.Collections.unmodifiableList(scopeProfiles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.scopeProfiles_ = scopeProfiles_;
      } else {
        result.scopeProfiles_ = scopeProfilesBuilder_.build();
      }
      result.schemaUrl_ = schemaUrl_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentelemetry.proto.profiles.v1development.ResourceProfiles) {
        return mergeFrom((io.opentelemetry.proto.profiles.v1development.ResourceProfiles)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentelemetry.proto.profiles.v1development.ResourceProfiles other) {
      if (other == io.opentelemetry.proto.profiles.v1development.ResourceProfiles.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (scopeProfilesBuilder_ == null) {
        if (!other.scopeProfiles_.isEmpty()) {
          if (scopeProfiles_.isEmpty()) {
            scopeProfiles_ = other.scopeProfiles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScopeProfilesIsMutable();
            scopeProfiles_.addAll(other.scopeProfiles_);
          }
          onChanged();
        }
      } else {
        if (!other.scopeProfiles_.isEmpty()) {
          if (scopeProfilesBuilder_.isEmpty()) {
            scopeProfilesBuilder_.dispose();
            scopeProfilesBuilder_ = null;
            scopeProfiles_ = other.scopeProfiles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            scopeProfilesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getScopeProfilesFieldBuilder() : null;
          } else {
            scopeProfilesBuilder_.addAllMessages(other.scopeProfiles_);
          }
        }
      }
      if (!other.getSchemaUrl().isEmpty()) {
        schemaUrl_ = other.schemaUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.opentelemetry.proto.profiles.v1development.ResourceProfiles parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.opentelemetry.proto.profiles.v1development.ResourceProfiles) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.opentelemetry.proto.resource.v1.Resource resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder> resourceBuilder_;
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     * @return The resource.
     */
    public io.opentelemetry.proto.resource.v1.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder setResource(io.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder setResource(
        io.opentelemetry.proto.resource.v1.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder mergeResource(io.opentelemetry.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            io.opentelemetry.proto.resource.v1.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public io.opentelemetry.proto.resource.v1.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    public io.opentelemetry.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            io.opentelemetry.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <pre>
     * The resource for the profiles in this message.
     * If this field is not set then no resource info is known.
     * </pre>
     *
     * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentelemetry.proto.resource.v1.Resource, io.opentelemetry.proto.resource.v1.Resource.Builder, io.opentelemetry.proto.resource.v1.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.util.List<io.opentelemetry.proto.profiles.v1development.ScopeProfiles> scopeProfiles_ =
      java.util.Collections.emptyList();
    private void ensureScopeProfilesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        scopeProfiles_ = new java.util.ArrayList<io.opentelemetry.proto.profiles.v1development.ScopeProfiles>(scopeProfiles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentelemetry.proto.profiles.v1development.ScopeProfiles, io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder, io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder> scopeProfilesBuilder_;

    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public java.util.List<io.opentelemetry.proto.profiles.v1development.ScopeProfiles> getScopeProfilesList() {
      if (scopeProfilesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scopeProfiles_);
      } else {
        return scopeProfilesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public int getScopeProfilesCount() {
      if (scopeProfilesBuilder_ == null) {
        return scopeProfiles_.size();
      } else {
        return scopeProfilesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ScopeProfiles getScopeProfiles(int index) {
      if (scopeProfilesBuilder_ == null) {
        return scopeProfiles_.get(index);
      } else {
        return scopeProfilesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder setScopeProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ScopeProfiles value) {
      if (scopeProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeProfilesIsMutable();
        scopeProfiles_.set(index, value);
        onChanged();
      } else {
        scopeProfilesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder setScopeProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder builderForValue) {
      if (scopeProfilesBuilder_ == null) {
        ensureScopeProfilesIsMutable();
        scopeProfiles_.set(index, builderForValue.build());
        onChanged();
      } else {
        scopeProfilesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder addScopeProfiles(io.opentelemetry.proto.profiles.v1development.ScopeProfiles value) {
      if (scopeProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeProfilesIsMutable();
        scopeProfiles_.add(value);
        onChanged();
      } else {
        scopeProfilesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder addScopeProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ScopeProfiles value) {
      if (scopeProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScopeProfilesIsMutable();
        scopeProfiles_.add(index, value);
        onChanged();
      } else {
        scopeProfilesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder addScopeProfiles(
        io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder builderForValue) {
      if (scopeProfilesBuilder_ == null) {
        ensureScopeProfilesIsMutable();
        scopeProfiles_.add(builderForValue.build());
        onChanged();
      } else {
        scopeProfilesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder addScopeProfiles(
        int index, io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder builderForValue) {
      if (scopeProfilesBuilder_ == null) {
        ensureScopeProfilesIsMutable();
        scopeProfiles_.add(index, builderForValue.build());
        onChanged();
      } else {
        scopeProfilesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder addAllScopeProfiles(
        java.lang.Iterable<? extends io.opentelemetry.proto.profiles.v1development.ScopeProfiles> values) {
      if (scopeProfilesBuilder_ == null) {
        ensureScopeProfilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scopeProfiles_);
        onChanged();
      } else {
        scopeProfilesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder clearScopeProfiles() {
      if (scopeProfilesBuilder_ == null) {
        scopeProfiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        scopeProfilesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public Builder removeScopeProfiles(int index) {
      if (scopeProfilesBuilder_ == null) {
        ensureScopeProfilesIsMutable();
        scopeProfiles_.remove(index);
        onChanged();
      } else {
        scopeProfilesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder getScopeProfilesBuilder(
        int index) {
      return getScopeProfilesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder getScopeProfilesOrBuilder(
        int index) {
      if (scopeProfilesBuilder_ == null) {
        return scopeProfiles_.get(index);  } else {
        return scopeProfilesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public java.util.List<? extends io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder> 
         getScopeProfilesOrBuilderList() {
      if (scopeProfilesBuilder_ != null) {
        return scopeProfilesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scopeProfiles_);
      }
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder addScopeProfilesBuilder() {
      return getScopeProfilesFieldBuilder().addBuilder(
          io.opentelemetry.proto.profiles.v1development.ScopeProfiles.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder addScopeProfilesBuilder(
        int index) {
      return getScopeProfilesFieldBuilder().addBuilder(
          index, io.opentelemetry.proto.profiles.v1development.ScopeProfiles.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of ScopeProfiles that originate from a resource.
     * </pre>
     *
     * <code>repeated .opentelemetry.proto.profiles.v1development.ScopeProfiles scope_profiles = 2;</code>
     */
    public java.util.List<io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder> 
         getScopeProfilesBuilderList() {
      return getScopeProfilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentelemetry.proto.profiles.v1development.ScopeProfiles, io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder, io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder> 
        getScopeProfilesFieldBuilder() {
      if (scopeProfilesBuilder_ == null) {
        scopeProfilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentelemetry.proto.profiles.v1development.ScopeProfiles, io.opentelemetry.proto.profiles.v1development.ScopeProfiles.Builder, io.opentelemetry.proto.profiles.v1development.ScopeProfilesOrBuilder>(
                scopeProfiles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        scopeProfiles_ = null;
      }
      return scopeProfilesBuilder_;
    }

    private java.lang.Object schemaUrl_ = "";
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_profiles" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @return The schemaUrl.
     */
    public java.lang.String getSchemaUrl() {
      java.lang.Object ref = schemaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schemaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_profiles" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @return The bytes for schemaUrl.
     */
    public com.google.protobuf.ByteString
        getSchemaUrlBytes() {
      java.lang.Object ref = schemaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_profiles" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @param value The schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_profiles" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaUrl() {
      
      schemaUrl_ = getDefaultInstance().getSchemaUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The Schema URL, if known. This is the identifier of the Schema that the resource data
     * is recorded in. Notably, the last part of the URL path is the version number of the
     * schema: http[s]://server[:port]/path/&lt;version&gt;. To learn more about Schema URL see
     * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
     * This schema_url applies to the data in the "resource" field. It does not apply
     * to the data in the "scope_profiles" field which have their own schema_url field.
     * </pre>
     *
     * <code>string schema_url = 3;</code>
     * @param value The bytes for schemaUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schemaUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.profiles.v1development.ResourceProfiles)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.profiles.v1development.ResourceProfiles)
  private static final io.opentelemetry.proto.profiles.v1development.ResourceProfiles DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentelemetry.proto.profiles.v1development.ResourceProfiles();
  }

  public static io.opentelemetry.proto.profiles.v1development.ResourceProfiles getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceProfiles>
      PARSER = new com.google.protobuf.AbstractParser<ResourceProfiles>() {
    @java.lang.Override
    public ResourceProfiles parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceProfiles(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceProfiles> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceProfiles> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentelemetry.proto.profiles.v1development.ResourceProfiles getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

