name: clang-tidy-review

on:
  workflow_run:
    workflows:
    - code-check
    types:
    - completed

jobs:
  clang-tidy-results:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - name: Download code-check artifacts
      uses: actions/github-script@v7
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
          });
          const matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "code-check-artifacts"
          })[0];
          const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: "zip",
          });
          const fs = require("fs");
          fs.writeFileSync("${{ github.workspace }}/code-check-artifacts.zip", Buffer.from(download.data));
    - name: Extract analysis results
      run: |
        unzip code-check-artifacts.zip -d /tmp/code-check-artifacts
    - name: Set environment variables
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require("fs");
          function exportVar(varName, fileName) {
              const val = fs.readFileSync("/tmp/code-check-artifacts/" + fileName, {
                  encoding: "ascii"
              }).trimEnd();
              core.exportVariable(varName, val);
          }
          exportVar("PR_ID", "pr-id.txt");
          exportVar("PR_HEAD_REPO", "pr-head-repo.txt");
          exportVar("PR_HEAD_SHA", "pr-head-sha.txt");
    - uses: actions/checkout@v4
      with:
        repository: ${{ env.PR_HEAD_REPO }}
        ref: ${{ env.PR_HEAD_SHA }}
        persist-credentials: false
        clean: false
    - name: Run clang-tidy-pr-comments action
      uses: platisd/clang-tidy-pr-comments@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clang_tidy_fixes: /tmp/code-check-artifacts/clang-tidy-fixes.yml
        pull_request_id: ${{ env.PR_ID }}
