name: Linter Checks

on:
  - push
  - pull_request

jobs:
  license-headers-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check license Headers
        uses: apache/skywalking-eyes/header@v0.6.0
