name: Linter Checks

on:
  - push
  - pull_request

jobs:
  check-license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check license headers
        uses: apache/skywalking-eyes/header@v0.6.0
